### ISSUE TITLE
Expose Lambda configuration options to Matano config

### ISSUE THREAD

**Issue by timoguin** [matanolabs/matano#85]
We need to be able to modify things like function CPU, memory, and timeouts. Figure out a good UX for exposing these options (maybe others as well) via the Matano config.

Maybe something like this in `matano.config.yml`:

```
functions:
  data_batcher:
    memory_size: 1024
    timeout: 80
    ephemeral_storage_size: 512
  metadata_writer:
    memory_size: 2048
    timeout: 200
    snapstart_apply_on: PublishedVersions
    ephemeral_storage_size: 1024
```
